name: Bazel Build & Test

on:
  
  push:
  
    branches: [ "dev","main" ]
  
  workflow_dispatch:
  
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: bazel test ... && bazel build ...
